export const TOGGLE_ON_SEARCHBAR_FOCUS = "toggle_on_searchbar_focus"
export const TOGGLE_OFF_SEARCHBAR_FOCUS = "toggle_off_searchbar_focus"
export const UPDATE_ALL_POSTS = "update_all_posts"
export const LOGGED_IN_TRUE = "logged_in_true"
export const LOGGED_IN_FALSE = "logged_in_false"
export const ADD_LOGGED_IN_UID = "add_logged_in_uid"
export const CLEAR_LOGGED_IN_UID = "clear_logged_in_uid"